./scripts/long_term_forecast/ETT_script/TimeDiff_test.sh
#./scripts/long_term_forecast/ETT_script/TimeDiff_ETTh1.sh
#./scripts/long_term_forecast/ETT_script/TimeDiff_ETTh2.sh
#./scripts/long_term_forecast/ETT_script/TimeDiff_ETTm1.sh
#./scripts/long_term_forecast/ETT_script/TimeDiff_ETTm2.sh
#./scripts/long_term_forecast/ECL_script/TimeDiff.sh
#./scripts/long_term_forecast/Exchange_script/TimeDiff.sh
#./scripts/long_term_forecast/Weather_script/TimeDiff.sh
#./scripts/long_term_forecast/Traffic_script/TimeDiff.sh